config/routes.rb
Rails.application.routes.draw do
  resources :formal
  devise_for :users, controllers: { registrations: 'registrations' }
  authenticated :user do
    root 'formal#index', as: :authenticated_root
  end

  get 'admin/user', to: 'admin#user'
  get 'admin/form', to: 'admin#form'
  get 'admin/export', to:'admin#export'
  post 'admin/export', to:'admin#create'

  match 'download', to: 'admin#download', as: 'download', via: :get

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/formal.rb
class Formal < ApplicationRecord
    validates :name, presence: true
    validates :company, presence: true
    validates :content, presence: true
    validates :note, presence: true

    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |customer|
            csv << customer.attributes.values_at(*column_names)
          end
        end
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :projects
  has_many :notes
  has_many :formals

  before_save :ensure_authentication_token
  after_create :send_welcome_email

  def name
    [first_name, last_name].join(" ")
  end
  def isAdmin
    current_user === "admin"
  end
  geocoded_by :last_sign_in_ip do |user, result|
    if !user.local? && geocode = result.first
      user.location = "#{geocode.city}, #{geocode.state}, #{geocode.country}"
      user.save
    end
  end

  def local?
    ["localhost", "127.0.0.1", "0.0.0.0"].include? last_sign_in_ip
  end

  def after_database_authentication
    GeocodeUserJob.perform_later self
  end

  private

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end


  
end

app/controllers/admin_controller.rb
require "csv"
class AdminController < ApplicationController
    def user
        @user = User.where(admin:nil)
    end
    def form
        @form = Formal.all
    end
    def export

        
    end
    def create
        time = params.require(:form).permit(:from,:to)
        i = 0
        @form =Formal.where("date >= ?",time[:from] ).where("date <= ?",time[:to] )
        file = "report.csv"
       CSV.open(file,"wb")  do |csv|
            csv << ["ID","Name","Date","Company","Content","Note"]
            @form.map do |form|
                i+=1
                csv << [i,form.name,form.date,form.company,form.content,form.note]
            end
        end
        send_file file, :type => 'csv', :disposition => 'attachment'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!


end

app/controllers/formal_controller.rb
class FormalController < ApplicationController
  def index
    @form = Formal.where(token:current_user.authentication_token)
  end

  def new
    @form = Formal.new
  end

  def edit
    @form = Formal.find(params[:id])
  end
  def create
    @user = current_user
    @form = Formal.new(params.require(:form).permit(:date,:company,:content,:note))
    @form.token = current_user.authentication_token
    @form.name = current_user.name
    if @form.save
      redirect_to formal_index_path
    else
      render 'new'
    end
  end
  def destroy
    @form = Formal.find(params[:id])
    @form.destroy
    if current_user.try(:admin?)
      redirect_to admin_form_path
    else
      redirect_to formal_index_path
    end
  end
  def update
    @form = Formal.find(params[:id])
    if @form.update(params.require(:formal).permit(:date,:company,:content,:note))
      if current_user.try(:admin?)
        redirect_to admin_form_path
      else
        redirect_to formal_index_path
      end
    else
      render 'edit'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,
                                 :password_confirmation,:phone_number)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password,:phone_number,
                                 :password_confirmation, :current_password)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_date(date)
    date_string = date.strftime("%B %d, %Y")
    date_human = time_ago_in_words(date)
    past_or_future = Time.now > date ? "ago" : "from now"
    "#{date_string} (#{date_human} #{past_or_future})"
  end
end

app/helpers/formal_helper.rb
module FormalHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/edit.html.erb
<H1> Edit user </H1>
<div class="container">
  <% if @user.length != 0 %>
  <% id = 1 %>
  <h1 style="text-align: center">List form</h1>
  <div class="form-center">
    <table>
      <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>email</th>
      </tr>

      <% @user.each do |form| %>
      <tr>
        <td><%= id %></td>
        <td><%= form.first_name %></td>
        <td><%= form.last_name %></td>
        <td><%= form.email %></td>
        <td><%= link_to 'Edit', edit_formal_path(form) %></td>
        <td><%= link_to 'Delete', formal_path(form),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% id +=1 %>
      <% end %>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/editform.html.erb
<h1>Edit form</h1>
<%= form_with(model: @form,local: true) do |form| %>
    <div class="container">
        <div class="row">
            <div>
                <p>
                    <%= form.label :Company %><br>
                    <%= form.text_field :company %>
                </p>
                <p>
                    <%= form.label :Date %><br>
                    <%= form.date_field :date %>
                </p>
                <p>
                    <%= form.label :Content %><br>
                    <%= form.text_field :content %>
                </p>
                <p>
                    <%= form.label :Note %><br>
                    <%= form.text_field :note %>
                </p>
                <p>
                    <%= form.submit "Submit"%>
                </p>
            </div>
        </div>
    </div>
<% end %>
<%= link_to 'Back', formal_index_path %>

app/views/admin/export.html.erb
<h2>Export</h2>

<%= form_with scope: :form,url: admin_export_path, local: true do |f| %>

<div class="row">
    <div class="form-group col-xs-8 col-md-3" >
        <%= f.label :From %>
        <%= f.date_field :from, class: "form-control",style:"text-align: center" %>
    </div>
</div>  
<div class="row">
    <div class="form-group col-xs-8 col-md-3" >
        <%= f.label :To %>
        <%= f.date_field :to, class: "form-control",style:"text-align: center" %>
    </div>
</div>
<p>
    <%= f.submit "Create"%>
</p>
<% end %>

app/views/admin/form.html.erb
<div class="container">
  <% if @form.length != 0 %>
  <% id = 1 %>
  <h1 style="text-align: center">List form</h1>
  <div class="form-center">
    <table>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Date</th>
        <th>Company</th>
        <th>Content</th>
        <th>Note</th>
      </tr>

      <% @form.each do |form| %>
      <tr>
        <td><%= id %></td>
        <td><%= form.name %></td>
        <td><%= form.date %></td>
        <td><%= form.company %></td>
        <td><%= form.content %></td>
        <td><%= form.note %></td>
        <td><%= link_to 'Edit', edit_formal_path(form) %></td>
        <td><%= link_to 'Delete', formal_path(form),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% id +=1 %>
      <% end %>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/user.html.erb
<div class="container">
  <% if @user.length != 0 %>
  <% id = 1 %>
  <h1 style="text-align: center">List form</h1>
  <div class="form-center">
    <table>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
      </tr>

      <% @user.each do |form| %>
      <tr>
        <td><%= id %></td>
        <td><%= form.name %></td>
        <td><%= form.email %></td>
        <td><%= form.phone_number%></td>
        <td><%= link_to 'Edit', '#'%></td>
        <td><%= link_to 'Delete', '#',
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% id +=1 %>
      <% end %>
    </table>
    <% end %>
  </div>
</div>

app/views/formal/edit.html.erb
<h1>Edit</h1>
<%= form_with(model: @form,local: true) do |form| %>
    <div class="container">
        <div class="row">
            <div>
                <p>
                    <%= form.label :Company %><br>
                    <%= form.text_field :company %>
                </p>
                <p>
                    <%= form.label :Date %><br>
                    <%= form.date_field :date %>
                </p>
                <p>
                    <%= form.label :Content %><br>
                    <%= form.text_field :content %>
                </p>
                <p>
                    <%= form.label :Note %><br>
                    <%= form.text_field :note %>
                </p>
                <p>
                    <%= form.submit "Submit"%>
                </p>
            </div>
        </div>
    </div>
<% end %>
<%= link_to 'Back', formal_index_path %>

app/views/formal/index.html.erb
<div class="container">
  <% if @form.length != 0 %>
  <% id = 1 %>
  <h1 style="text-align: center">List form</h1>
  <div class="form-center">
    <table>
      <tr>
        <th>ID</th>
        <th>Company</th>
        <th>Date</th>
        <th>Content</th>
        <th>Note</th>
      </tr>

      <% @form.each do |form| %>
      <tr>
        <td><%= id %></td>
        <td><%= form.company %></td>
        <td><%= form.date %></td>
        <td><%= form.content %></td>
        <td><%= form.note %></td>
        <td><%= link_to 'Edit', edit_formal_path(form) %></td>
        <td><%= link_to 'Delete', formal_path(form),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% id +=1 %>
      <% end %>
    </table>
    <% end %>
  </div>
    <br>
   <%= button_to "Add", new_formal_url, method: :get,class:'button_log'%>
</div>    

app/views/formal/new.html.erb
<h1>Fill the Form below</h1>
<%= form_with scope: :form,url: formal_index_path, local: true do |form| %>
    <div class="container">
        <div class="row">
            <div>
                <p>
                    <%= form.label :Company %><br>
                    <%= form.text_field :company %>
                </p>
                <p>
                    <%= form.label :Date %><br>
                    <%= form.date_field :date %>
                </p>
                <p>
                    <%= form.label :Content %><br>
                    <%= form.text_field :content %>
                </p>
                <p>
                    <%= form.label :Note %><br>
                    <%= form.text_field :note %>
                </p>
                <p>
                    <%= form.submit "Submit"%>
                </p>
                <%= link_to 'Back', formal_index_path %>
            </div>
        </div>

    </div>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to Projects</h1>

<p>
  <%= link_to "Sign in", new_user_session_path %> or
  <%= link_to "Sign up", new_user_registration_path %> to continue.
</p>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name == 'notice' ? 'success' : 'warning' %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if current_user.try(:admin?)%>
        <ul class="nav navbar-nav navbar-center">
          <li><%= link_to "User", admin_user_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-center">
          <li><%= link_to "ListForm", admin_form_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-center">
          <li><%= link_to "Export", admin_export_path , method:"get" %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav">
        <li><%= link_to "Formal", formal_index_path %></li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.name, edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projects</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <div class="container">
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>